# Power BI REST API pipeline.
# Extracts refresh history for all datasets in all Power BI workspaces
# and saves to a CSV/JSON file in Azure Blob Storage.
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight (UTC) refresh
  branches:
    include:
      - main
  always: true

pool:
  vmImage: ubuntu-latest

variables:
  # $TenantId, $AppId, $AppSecret are set as pipeline variables
  - group: pbi-rest-api-variables

steps:

- task: PowerShell@2
  displayName: 'Get Refresh History'
  name: GetRefreshHistory
  inputs:
    pwsh: true
    targetType: inline
    script: |
      $TenantId = "$(TenantId)"
      $AppId = "$(AppId)"
      $AppSecret = ConvertTo-SecureString "$(AppSecret)" -AsPlainText -Force

      $RefreshHistory = @()
      ./Get-RefreshHistory.ps1 `
        -TenantId $TenantId `
        -AppId $AppId `
        -AppSecret $AppSecret `
        -OutputJsonPath "refresh-history.json" `
        -OutputCsvPath "refresh-history.csv" `
        -OutputConsole:$true `
        -OutputGrid:$true `
        -maxDatasets 500 `
        -maxRefreshes 500 `
        -StartDate "1900-01-01" `
        -EndDate "2200-01-01" `
        -RefreshHistory ([ref]$RefreshHistory)

      # Set the output variable for use in the next step
      Write-Host "##vso[task.setvariable variable=RefreshHistory]$RefreshHistory"

- task: PublishPipelineArtifact@1
  displayName: 'Publish Refresh History'
  name: PublishRefreshHistory
  condition: gt(variables['RefreshHistory'].Count, 0)
  inputs:
    targetPath: 'refresh-history.json'
    artifactName: 'refresh-history'
    publishLocation: 'pipeline'
    