# Power BI REST API pipeline.
# Extracts refresh history for all datasets in all Power BI workspaces
# and saves to a CSV/JSON file in Azure Blob Storage.
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight (UTC) refresh
  branches:
    include:
      - main
  always: true

pool:
  vmImage: ubuntu-latest

variables:
  # $TenantId, $AppId, $AppSecret are set as pipeline variables
  - group: pbi-rest-api-variables

jobs:

- job: GetRefreshHistoryJob
  steps:
  - task: PowerShell@2
    displayName: 'Get Refresh History'
    name: GetRefreshHistoryStep
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $TenantId = "$(TenantId)"
        $AppId = "$(AppId)"
        $AppSecret = ConvertTo-SecureString "$(AppSecret)" -AsPlainText -Force

        $RefreshHistory = @()
        ./Get-RefreshHistory.ps1 `
          -TenantId $TenantId `
          -AppId $AppId `
          -AppSecret $AppSecret `
          -OutputJsonPath "refresh-history.json" `
          -OutputCsvPath "refresh-history.csv" `
          -OutputConsole:$true `
          -maxDatasets 500 `
          -maxRefreshes 500 `
          -StartDate "1900-01-01" `
          -EndDate "2200-01-01" `
          -RefreshHistory ([ref]$RefreshHistory)

        # Set the output variable 'RefreshHistory' for use in the next job
        Write-Host "##vso[task.setvariable variable=RefreshHistory;isOutput=true]$RefreshHistory"
        Write-Host "##vso[task.setvariable variable=RefreshHistoryCount;isOutput=true]$($RefreshHistory.Count)"

- job: PublishRefreshHistoryJob
  dependsOn: GetRefreshHistoryJob
  condition: gt(dependencies.GetRefreshHistoryJob.outputs['GetRefreshHistoryStep.RefreshHistoryCount'], 0)
  steps:
  # - task: PublishPipelineArtifact@1
  #   displayName: 'Publish Refresh History to Azure Pipelines'
  #   name: PublishRefreshHistory
  #   inputs:
  #     targetPath: 'refresh-history.json'
  #     artifactName: 'refresh-history'
  #     publishLocation: 'pipeline'
  - task: PowerShell@2
    displayName: 'Get Refresh History'
    name: GetRefreshHistoryStep
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $RefreshHistory = "$(GetRefreshHistoryJob.RefreshHistory)"
        $RefreshHistory | fl
